project_id = "rmhikdxraoiskrkxspds"

[functions.search-weather]
verify_jwt = false

[functions.search-market-prices]
verify_jwt = false

[functions.chat-farming]
verify_jwt = false

[functions.crop-suggestions]
verify_jwt = false
